### ISSUE TITLE
Add availability to a search engine redirection

### ISSUE THREAD

**Issue by CAESARSNOOT** [NovaAppsInc/fracital-proxy#1]
### Search engine redirection

**Working on adding availability to search the string that is the search bar that isn't a website**
i.e. `No One Like You by Scorpions` will redirect to a search engine with the search for `No One Like You by Scorpions`

**Comment by CAESARSNOOT** [comment]
> It's built in:
> https://fracital.org/kb/gateway?url=No One Like You by Scorpions

yeah but detecting if if not a url then send user to that page, I'm a bit stupid lol.

**Comment by boomermath** [comment]
It can be done pretty easily. Since valid url's are not allowed to have spaces in them, if the value in the url bar has a spaces + no .com ending etc, then its a query which can be encoded with something like `https://google.com/search?q=${encodeURIComponent(query)}`

**Comment by Nebelung-Dev** [comment]
https://fracital.org/kb/gateway?url=No%20One%20Like%20You%20by%20Scorpions
