### ISSUE TITLE
Does not load some websites 

### ISSUE THREAD

**Issue by CringyLeftist** [NovaAppsInc/fracital-proxy#24]
it seems to work for almost every thing but I can not log in to my google account and the tiktok website (https://www.tiktok.com/en/) does not load instead I get a message (RangeError: Failed to construct 'Response': The status provided (0) is outside the range [200, 599) 
I would be thankful if you fixed this bug best of luck. (: 👍

**Comment by NovaAppsInc** [comment]
if we allowed you to sign into to google google would instantly mark our site as dangerous
