### ISSUE TITLE
Proxy Down

### ISSUE THREAD

**Issue by monkpunch3000** [NovaAppsInc/fracital-proxy#8]
Just won't open and keeps going back to origin is unreachable.

**Comment by PineappleDoge** [comment]
Same issue here, hope it gets resolved soon :(

**Comment by Acidicblaze779** [comment]
As well as me, this is one of the best proxies I've seen, so hopefully it gets fixed

**Comment by NovaAppsInc** [comment]
The proxy is down and I have to buy a new vps, you can help support me and keep the proxy up over on the patreon https://patreon.com/fracital

sorry for the inconveniences
